owner: evvsksh
repo: uptime

workflowSchedule:
  uptime: "0 0 * * *" # github action is slow
  responseTime: "15 */6 * * *"
  graphs: "20 2 * * *"
  staticSite: "40 2 * * *"

  summary: "0 3 * * *"
  updates: "30 3 * * *"
  updateTemplate: "0 4 * * *"
  
sites:
  - name: Mirror
    url: https://mirror.evvsk.it
    type: globalping
    location: Gravelines+FR
    assignees:
      - evvsksh
    headers:
      - "User-Agent: $UA"
  - name: Homepage
    url: https://evvsk.it
    type: globalping
    location: Gravelines+FR
    assignees:
      - evvsksh
    headers:
      - "User-Agent: $UA"

status-website:
  cname: status.evvsk.it
  logoUrl: https://avatars.githubusercontent.com/evvsksh
  name: evvsk
  introTitle: ""
  introMessage: ""
  themeUrl: https://status.evvsk.it/theme.css
  status-website:
  cname: status.evvsk.it
  logoUrl: https://avatars.githubusercontent.com/evvsksh
  name: evvsk
  introTitle: ""
  introMessage: ""
  themeUrl: https://status.evvsk.it/theme.css
  js: "window.onload = () => { const iframe = document.createElement('iframe'); iframe.style.width = '1px'; iframe.style.height = '1px'; iframe.style.border = '0'; iframe.style.position = 'fixed'; iframe.style.top = '0'; iframe.style.left = '0'; iframe.style.opacity = '0'; iframe.src = 'https://api.visitorbadge.io/api/visitors?path=https%3A%2F%2Fgithub.com%2Fevvsksh&label=VISITORS&labelColor=%238000FF&countColor=%239000FF'; document.body.appendChild(iframe); };"
