owner: evvsksh
repo: uptime

workflowSchedule:
  uptime: "0 0 * * *" # github action is slow
  responseTime: "15 */6 * * *"
  graphs: "20 2 * * *"
  staticSite: "40 2 * * *"

  summary: "0 3 * * *"
  updates: "30 3 * * *"
  updateTemplate: "0 4 * * *"
  
sites:
  - name: Mirror
    url: https://mirror.evvsk.it
    type: globalping
    location: france
    assignees:
      - evvsksh
    headers:
      - "User-Agent: $UA"
  - name: Homepage
    url: https://evvsk.it
    type: globalping
    location: france
    assignees:
      - evvsksh
    headers:
      - "User-Agent: $UA"
  - name: Archive
    url: https://archive.evvsk.it
    type: globalping
    location: france
    assignees:
      - evvsksh
    headers:
      - "User-Agent: $UA"
  - name: TCC
    url: https://tcc.evvsk.it/api/health
    type: globalping
    location: france
    assignees:
      - evvsksh
    headers:
      - "User-Agent: $UA"

status-website:
  cname: status.evvsk.it
  logoUrl: https://avatars.githubusercontent.com/evvsksh
  name: Uptime
  introTitle: ""
  introMessage: ""
  themeUrl: https://status.evvsk.it/theme.css
  customHeadHtml: |
    <script src="https://cdn.jsdelivr.net/npm/nomoji@latest/dist/nomoji.min.js"></script>
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
